name: confident_voice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  record: ^5.2.0  # Recording library
  audioplayers: ^6.1.0  # For audio playback
  permission_handler: ^11.2.0  # For handling app permissions
  cupertino_icons: ^1.0.8  # iOS-specific icons
  flutter_audio_waveforms: ^1.0.0 
  audio_waveforms: ^1.2.0 
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  sqflite: ^2.4.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.7
  image_picker: ^1.1.2
  file_picker: ^8.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/Creativity_pana.png
    - assets/images/image_placeholder.png
    - assets/images/illustrationSign.png
    - assets/images/googleIcon.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/iaHelp.png
    - assets/images/iaHelp2.png
    - assets/images/exo1.png
    - assets/images/exo2.png
    - assets/images/exo3.png
    - assets/images/exo31.png
    - assets/images/exo32.png
    - assets/images/exo33.png
    - assets/images/exo34.png
    - assets/images/image_placeholder.png
    - assets/images/page1.png
    - assets/images/page2.png
    - assets/images/page3.png
    - assets/images/profile.png 
    - assets/images/profile.png
